### ISSUE TITLE
Can not find autostart in LXDE-pi

### ISSUE THREAD

**Issue by ScobyDoo** [reuterbal/photobooth#102]
Hello

I would like to extend the autostart file in LXDE-pi, so that the program starts automatically when booting. only I can not find the file Autostart in the specified directory.
also the file LXPE-pi is not in the "lxsession" but in the LXpanel.

**Comment by reuterbal** [comment]
Are you on Raspbian? If folder and file are not there, maybe try creating them.

**Comment by ScobyDoo** [comment]
pi@raspberrypi:~/.config $ dir
chromium  gpicview  leafpad  lxterminal     qpdfview	    user-dirs.locale
dconf	  gtk-2.0   libfm    mimeapps.list  QtProject.conf  vlc
geany	  gtk-3.0   lxpanel  pcmanfm	    user-dirs.dirs  xarchiver

This is the ".config" on Raspbian!
