### ISSUE TITLE
[Success Story] French wedding in June 2018

### ISSUE THREAD

**Issue by wikijm** [reuterbal/photobooth#11]
Hi @reuterbal,

Thanks to your wonderful project, I had the opportunity to offer to my sister a great home photobooth for her wedding.
It also allowed me to do a joint activity with my (future) brother-in-law, who was in charge of assembling the wooden form-work and everything that allowed me to integrate the electronics, the Raspberry and the camera.

**Hardware:**
 - Device:   Raspberry Pi 2 B
 - Camera:   Canon EOS 550D + EFS 18-55mm
 - GPIO:     Yes

**Additional Equipment:**

| Picture | Name | Price
| :--------------: | :--------------: | :--------------:
| ![91f0njuvwxl _sl1500_](https://user-images.githubusercontent.com/10724809/41472315-56116658-70b6-11e8-9738-02f4b68e675e.jpg) | [Canon EOS 550D 18 Mpix SLR Digital Camera Lens Kit 18-55mm IS Black](https://www.amazon.fr/dp/B01MCUQJGC/ref=sspa_dk_detail_1?psc=1&pd_rd_i=B01MCUQJGC&pf_rd_m=A1X6FK5RDHNB96&pf_rd_p=1370598536209589035&pf_rd_r=QDTSJQSS77P85KVAK9Z1&pd_rd_wg=nrfGc&pf_rd_s=desktop-dp-sims&pf_rd_t=40701&pd_rd_w=PtHKu&pf_rd_i=desktop-dp-sims&pd_rd_r=f75fea77-7021-11e8-80b3-9131ac438cd8) | 443,99 €
| ![61utbi8djkl _sl1500_](https://user-images.githubusercontent.com/10724809/41472278-3cb9dc4e-70b6-11e8-829e-87118677cd3f.jpg) | [Aukru Raspberry Pi 3 Power supply 5V 3000mA with switch](https://www.amazon.fr/Aukru-Chargeur-Adaptateur-Alimentation-Raspberry/dp/B01M58O9M9/ref=sr_1_19?ie=UTF8&qid=1529013208&sr=8-19&keywords=raspberry%2Bpi%2B2&th=1) | 9,99 €
| ![51w8pew4d7l _sl1024_](https://user-images.githubusercontent.com/10724809/41472338-67af2ce2-70b6-11e8-9c1d-108310f6f967.jpg) | [Waveshare 7inch HDMI LCD (C) Capacitive Touch Screen Display Supports Various Systems for All Ver. Raspberry pi 3 Model B/ 2B/B+/B/A BeagleBone Black Banana Pi/Pro Video Photo Kit with Bicolor Case](https://www.amazon.fr/Waveshare-LCD-HDMI-r%C3%A9solution-Raspberry/dp/B01HPV7M4I/ref=sr_1_58?ie=UTF8&qid=1529013265&sr=8-58&keywords=raspberry%2Bpi%2B2&th=1)  | 67,99 €
| ![81qbr-x4nsl _sl1500_](https://user-images.githubusercontent.com/10724809/41472374-8878d9f0-70b6-11e8-90bd-f22dd64b2826.jpg) |  [MakerStack 150Pcs 10CM Multicolore Dupont Wire Jumper](https://www.amazon.fr/MakerStack-Multicolore-Solderless-BreadBoard-Raspberry/dp/B07D5XF44S/ref=sr_1_65_sspa?ie=UTF8&qid=1529013292&sr=8-65-spons&keywords=raspberry%2Bpi%2B2&th=1)  | 9,99 €
| ![s-l1600](https://user-images.githubusercontent.com/10724809/41472393-9d5992d8-70b6-11e8-84dc-791b67e8da1e.jpg) | [Long Length Arcade Game HAPP Style Push Button for Mame and Jamma 6 Colors](https://www.ebay.fr/itm/Long-Length-Arcade-Game-HAPP-Style-Push-Button-for-Mame-and-Jamma-6-Colors/132625572130?hash=item1ee119a122:g:yW4AAOSw~Bha~Ovi) | 1,29 €
| ![613oo8 d5ul _sl1001_](https://user-images.githubusercontent.com/10724809/41472439-baab62b2-70b6-11e8-812f-9594dda0d418.jpg) | [DR-E8 LP-E8 LPE8 Dummy Batterie + 5V-8.4V Câble USB Pilote ACK-E8 + 5V3A Adaptateur Chargeur pour Canon EOS 550D 600D 650D 700D T4i X6i](https://www.amazon.fr/gp/product/B0748G9GPG/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1) | 22,99 €
| ![31qko89arll](https://user-images.githubusercontent.com/10724809/41472462-c9255578-70b6-11e8-915f-06975b470486.jpg) | [StarTech.com USB2HABM1 Câble Mini USB 2.0 30 cm A vers Mini B M/M](https://www.amazon.fr/StarTech-com-USB2HABM1-C%C3%A2ble-Mini-vers/dp/B002L5U7N2/ref=sr_1_3?ie=UTF8&qid=1529015019&sr=8-3&keywords=mini-usb+cable) | 2,39 €

**Schema:**
![photobooth](https://user-images.githubusercontent.com/10724809/41499995-3e31a1cc-718a-11e8-8743-20ed8c833bdd.png)
![raspberry-pi-gpio-layout-model-b-plus-rotated-2700x900](https://user-images.githubusercontent.com/10724809/41791324-b79aa00c-7655-11e8-93a5-b44f14b9abba.png)
(Contact me if you want the .vsdx file)

**Software:**
 - OS: Raspbian GNU/Linux 9 (stretch) (partial result of `cat /etc/*-release` command)
 - Python: 2.7.13 (result of `python --version` command)

**Modifications:**
To take care of remote maintenance, I added a Wifi key which allowed me to create an access point and connect me in SSH in order to :

- [Control the Raspberry remotely by SSH with the JuiceSSH application (Android)](https://play.google.com/store/apps/details?id=com.sonelli.juicessh)
- [Control the Raspberry remotely by VNC with the VNC Viewer application (Android)](https://play.google.com/store/apps/details?id=com.realvnc.viewer.android)
- [Get the pictures on my smartphone with the AndFTP application (Android)](https://play.google.com/store/apps/details?id=lysesoft.andftp)

**Problems:**
   - Please see below, more to come with experience and time

**Pictures:**
![20180530_165922](https://user-images.githubusercontent.com/10724809/41441585-916d0c44-7033-11e8-9b28-b53e24183133.jpg)
![20180603_094421](https://user-images.githubusercontent.com/10724809/41473272-13d76582-70b9-11e8-98d0-ead60a01c40f.jpg)
![20180603_094449](https://user-images.githubusercontent.com/10724809/41441599-9c090c0c-7033-11e8-96fc-bbc789c55390.jpg)
![20180603_094501](https://user-images.githubusercontent.com/10724809/41441603-9f1e6748-7033-11e8-91b8-d6597f98e334.jpg)

If you have any questions or need feedback, please do not hesitate to contact me 😉

**Comment by reuterbal** [comment]
Hi @wikijm

thanks a ton for that detailed story! Your photobooth looks incredible.
Have you experienced any software glitches/problems during the event which could have been prevented? I'm always trying to make the software more stable.

**Comment by wikijm** [comment]
I had a rather sad problem, but with a revisited version of your script in order to make only one image.

Indeed, the marriage took place over 2 days (From 17h the 1st day to 3h the 2nd day). When the script was launched, the folder corresponding to the 1st date was created, but this was not the case for the 2nd. Result: All the photos of the 2nd day were lost (loss estimated at about twenty images according to the counter of trigger of the reflex).

I will take some time today and probably this weekend to adapt my success story to your template 😉

**Comment by reuterbal** [comment]
Don't worry about the template - your feedback is very much appreciated in the current form!
The directory problem is very unfortunate. In fact, I should check whether this could happen with the current version as well!

**Comment by wikijm** [comment]
Updated to match [success-story](https://github.com/reuterbal/photobooth/blob/master/.github/ISSUE_TEMPLATE/success-story.md) template :sunglasses:

**Comment by thyristor59** [comment]
hello, i'm so sorry for my english, i'm french... and i would like know change english text in french text...

it's for a weeding to my best friend !

I all ready install camera, print and photobooth application!
I start on raspberry pi, i'm a NOOB =)

thanks

**Comment by thyristor59** [comment]
bonsoir, je me permet de te transmettre mon mail: pierre-v@live.fr pour éviter de flood le topic!

j'ai en matériel:
- raspberry pi 3B, 
- nikon D3200, 
- et pour le moment en imprimante une canon pixma ip 2850 pour tester!

grâce au tuto, j'ai tout installé et le logiciel est fonctionnel, cependant j'aimerais avoir le texte en français,  je commence a peine avec le raspberry, comme dit précédemment.
Je ne comprends pas comment modifier les fichiers =(

je mis prends a l'avance... Juin 2019...
Je veux surtout comprendre ce que je fais, j'ai soif d'apprendre, toutes aides/conseils me réjouirais!

cordialement =)

**Comment by reuterbal** [comment]
As this is included in the Wiki now, I'll close this.

**Comment by richard69800** [comment]
hello, i live in france, but i would like to knox if you could send to me the plan to do this photobooth please? is it possible to connect a printer whith your system? 
thank you for the answer, best regards from france.

i wish, you will answer me ^^

richard
mail: richardvartanian69@gmail.com

**Comment by wikijm** [comment]
> 
> 
> hello, i live in france, but i would like to knox if you could send to me the plan to do this photobooth please? is it possible to connect a printer whith your system?
> thank you for the answer, best regards from france.
> 
> i wish, you will answer me ^^
> 
> richard
> mail: [richardvartanian69@gmail.com](mailto:richardvartanian69@gmail.com)

I'll send you an email to discuss 😉
