### ISSUE TITLE
Autostart suddenly doesn't work.

### ISSUE THREAD

**Issue by MarioJanssen27** [reuterbal/photobooth#111]
Autostart suddenly doesn't work.  2 Error message is displayed:

Error: (-1) unspecified Error
Error: (-53) Cloud Not Claim the USB device

The only thing I changed was the statement from the problem.
 [https://github.com/reuterbal/photobooth/issues/80#issuecomment-452198384 ](url)

What do I have to change to make the autostart work again?

**Comment by MarioJanssen27** [comment]
Problem gelöst. Kamera fokussierte  nicht.

**Comment by wikijm** [comment]
Hi @MarioJanssen27,

Vielen Dank für dein Feedback. Jetzt, da alles funktioniert, schließe ich das Problem.

-------------------------------------------------------------------------------------------

Thanks for your feedback. Now that everything's works, I close the issue.
