### ISSUE TITLE
Is it possible to print 2 copies per page ?

### ISSUE THREAD

**Issue by kun93** [reuterbal/photobooth#112]
Is there anyway to modify cups or add something in the config to print 2 copies per page (2x6 x 2) ? I would like to get a photobooth style print on a 4x6 photo paper. Similar to the image on https://github.com/reuterbal/photobooth/issues/86

**Comment by oelegeirnaert** [comment]
Hi @kun93 ,

Check the file: https://github.com/reuterbal/photobooth/blob/79c7ef1affab78b947fe3940f2d70dd646ccb49c/photobooth/camera/__init__.py#L173

On line 173 I've added some code to do the same.
This will take the original picture, and copy it.

**Comment by kun93** [comment]
@oelegeirnaert thanks so much for this ! I’ll try it out tonight .

**Comment by reuterbal** [comment]
Thanks @oelegeirnaert for suggesting this. As there were no follow-ups, I assumed it worked and I'll close this.

**Comment by alopezbu** [comment]
@oelegeirnaert is it possible that the "second copy" could be in black and white and the fisrt one in colour?

**Comment by oelegeirnaert** [comment]
Not tested but I think it should work by replace line 175 with:

`new_image.paste(picture.convert('LA'), (self._pic_dims.outputSize[0],0))`
