### ISSUE TITLE
can't install Canon Selphy cp1300

### ISSUE THREAD

**Issue by ScobyDoo** [reuterbal/photobooth#116]
I have built a photobooth for my silver wedding!
Everything works great too. Now I have bought a Canon printer and should print out the photos. I have followed the instructions, but can not select the driver for the Selphy cp1300.

As a local printer, he is displayed to me!

Raspberry Pi 3B+
 - Canon EOS 500D
- Canon Selphy cp1300

- I created the two files
- link written in the sources.list
![2019-04-17-095842_1920x1200_scrot](https://user-images.githubusercontent.com/47593287/56271000-ba484d80-60f7-11e9-936e-f649654d3c8b.png)

- can not select a driver
![2019-04-17-100223_1920x1200_scrot](https://user-images.githubusercontent.com/47593287/56271097-f24f9080-60f7-11e9-825d-f46bf820f373.png)

- Here he indicates an error
![2019-04-17-100529_1920x1200_scrot](https://user-images.githubusercontent.com/47593287/56271277-6722ca80-60f8-11e9-8468-1d1244c70412.png)

- Here he indicates an error
![2019-04-17-100357_1920x1200_scrot](https://user-images.githubusercontent.com/47593287/56271211-35a9ff00-60f8-11e9-82c1-6a374da9d7f1.png)

Thank you in advance for the help

**Comment by reuterbal** [comment]
There is a white space missing before "buster" in your first screenshot.
