### ISSUE TITLE
Take multiple photos in succession

### ISSUE THREAD

**Issue by awmt102** [reuterbal/photobooth#117]
Is it possible to configure to take more than one photo per button press? i.e. like how a high street photobooth generally takes four photos one after the other.

I am looking at modifying the code to do this, but if anyone can point me at a simple way that would be ideal. Alternatively give me an idea of where in the code I should be looking.

UPDATE: Apologies - i figured it out.

**Comment by wikijm** [comment]
Hi @awmt102,

Could you please share your solution then close the issue?

**Comment by awmt102** [comment]
The solution was simply to set "keep single shots" to true and "Number of photos per shot to 2 x 2.
