### ISSUE TITLE
Official Raspberry Pi 7" Tochscreen

### ISSUE THREAD

**Issue by apm1007** [reuterbal/photobooth#118]
installed it on raspberry pi 3b with official 7" Touchscreen. im not able to set the options because the mask ist far to big. no way to resize. Any ideas? thx
![grafik](https://user-images.githubusercontent.com/11927080/56463351-a55b0b00-63d2-11e9-9d85-31f4ef4fe7d3.png)
solved it by changing the default config. after that the window resized correctly!

**Comment by xiberger** [comment]
please close the issue!
