### ISSUE TITLE
Margins. 

### ISSUE THREAD

**Issue by roboticsguy1988** [reuterbal/photobooth#133]
I would like to be able to add margins for the top, bottom, left, and right side of the page. The images should respect the margins but NOT the background. It seems the thumbnails are right up to the left and right edges of the paper and I would like to put a 40px margin on the left and right without adding 40px in-between each picture.

**Comment by reuterbal** [comment]
The config values `min_dist_x` and `min_dist_y` are adding margins. Simply increase these values.

**Comment by roboticsguy1988** [comment]
If I change the x does that affect both left and right? And y affect both top and bottom?

**Comment by reuterbal** [comment]
Yes.

**Comment by roboticsguy1988** [comment]
This is not a sufficient solution. This puts space in-between each picture. I should have a left, top, right, and bottom margin. I only want additional space on the left and right of the page i do not want additional space in-between the pictures.

**Comment by reuterbal** [comment]
Now I understood - I will see if I can do something this evening.

**Comment by roboticsguy1988** [comment]
Awesome! Thanks so much. If you don't mind telling me what file you modified to do it, I would like to see the differences.  Python is something I hope to learn.

**Comment by reuterbal** [comment]
I added the ability to have different margins in the interior and exterior. Please try the development branch (see https://github.com/reuterbal/photobooth/wiki/Tips-and-tricks#switch-to-development-branch)
The changes can be seen here: https://github.com/reuterbal/photobooth/commit/8b14ec29141b4b519bf80350012d266754905e9f
