### ISSUE TITLE
Photobooth extension

### ISSUE THREAD

**Issue by AcidCool83** [reuterbal/photobooth#136]
**Describe your photobooth**
The photobooth is tucked inside a briefcase and will be used within 15 days at a friend's wedding

**Hardware (please complete the following information):**
 - Device: Raspberry Pi 3B+
 - Camera: PiCamera
 - GPIO: Yes
 
 **Additional equipment**
  - Flash/Light
  - button

**Modifications:**
**Problems:**

good afternoon, 

first of all congratulate you for the great job you have done with this program. I'm sorry if my English is not very good, that's what the Google translator has to use. 

I am implementing your program and so far it is going away well but I would like to know if it could be included or have been included in another branch, a flash that lights up in the capture of the image and a button to be able to perform the program options without needing mouse. That is, one button to launch the option to print and another button to return to the initial state. I have already enabled the trigger button and it works perfect. 
I have seen that they have already asked something similar but since my is not good, I do not know much or nothing.

**Comment by reuterbal** [comment]
This has been asked before, see #44, #58
