### ISSUE TITLE
Could not find a version that satisfies the requirement opencv-python

### ISSUE THREAD

**Issue by poldixd** [reuterbal/photobooth#151]
**Describe the bug**

When I run the `pip install -e .` command I got this error:

```
  ERROR: Could not find a version that satisfies the requirement opencv-python (from photobooth==0.5.dev3+g40f1cda) (from versions: none)
ERROR: No matching distribution found for opencv-python (from photobooth==0.5.dev3+g40f1cda)

```

**To Reproduce**

Follow the `INSTALL.md` instructions till `pip install -e .` .

**Hardware (please complete the following information)**

 - Device Raspberry Pi 3B
 - Camera Canon EOS 400D
 - GPIO: No

**Software (please complete the following information)**

 - OS Raspian 10
 - Python version 3.7.3
 
 **Installed packages**
 
 ```
arandr==0.1.9
asn1crypto==0.24.0
automationhat==0.1.0
blinker==1.4
blinkt==0.1.2
buttonshim==0.0.2
Cap1xxx==0.1.3
certifi==2018.8.24
chardet==3.0.4
Click==7.0
colorama==0.3.7
colorzero==1.1
configparser==3.5.0b2
cookies==2.2.1
cryptography==2.6.1
drumhat==0.1.0
entrypoints==0.3
enum34==1.1.6
envirophat==1.0.0
ExplorerHAT==0.4.2
Flask==1.0.2
fourletterphat==0.1.0
funcsigs==1.0.2
gpiozero==1.5.1
gyp==0.1
idna==2.6
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.10
keyring==17.1.1
keyrings.alt==3.1.1
MarkupSafe==1.1.0
mcpi==0.1.1
microdotphat==0.2.1
mock==2.0.0
mote==0.0.4
motephat==0.0.2
numpy==1.16.2
oauthlib==2.1.0
olefile==0.46
pantilthat==0.0.7
pbr==4.2.0
phatbeat==0.1.1
pianohat==0.1.0
picamera==1.13
picraft==1.0
piglow==1.2.4
pigpio==1.42
Pillow==5.4.1
pycairo==1.16.2
pycrypto==2.6.1
pyflakes==2.0.0
pygame==1.9.4.post1
PyGObject==3.30.4
pyinotify==0.9.6
PyJWT==1.7.0
pyOpenSSL==19.0.0
pyserial==3.4
pyxdg==0.25
rainbowhat==0.1.0
requests==2.21.0
requests-oauthlib==1.0.0
responses==0.9.0
RPi.GPIO==0.6.5
RTIMULib==7.2.1
scrollphat==0.0.7
scrollphathd==1.2.1
SecretStorage==2.3.1
sense-emu==1.1
sense-hat==2.2.0
simplejson==3.16.0
six==1.12.0
skywriter==0.0.7
sn3218==1.2.7
spidev==3.3
touchphat==0.0.1
twython==3.7.0
unicornhathd==0.0.4
urllib3==1.24.1
Werkzeug==0.14.1
 ```

**Comment by SkiTheSlicer** [comment]
I mentioned the same issue on the [Raspberry Pi 4 thread](https://github.com/reuterbal/photobooth/issues/142#issuecomment-506899221). Piwheels is still not caught up on building all the pip packages for ARM and Raspbian Buster. Hopefully it's just a matter of waiting it out.

EDIT: Their latest blog post notes they hope to be caught up by Monday.

**Comment by reuterbal** [comment]
If you want to use the Canon EOS 400D you won't require OpenCV. In that case, you can temporarily remove `opencv-python` from https://github.com/reuterbal/photobooth/blob/40f1cdadcc8cff0c142fe1d4f14813f07c5a656f/setup.py#L186-L193
and re-run the install command.

Hopefully the other packages are already available for Buster. Please report back.

**Comment by oelegeirnaert** [comment]
I'll try this solution this evening as well...

**Comment by poldixd** [comment]
After I removed `opencv-python` I got this error `photobooth requires Python '>=3.5' but the running Python is 2.7.16`. Python  version 2 (`python`) and 3 (`python3`) is preinstalled on raspbian. I'm a beginner... How can I set version 3 as the "default" python?

**Update**

ok, it was `pip3 install -e .` 😂 Now everything was installed.

```
pi@raspberrypi:~/Desktop/photobooth $ pip3 install -e .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Obtaining file:///home/pi/Desktop/photobooth
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from photobooth==0.5.dev3+g40f1cda.d20190711) (5.4.1)
Collecting gphoto2 (from photobooth==0.5.dev3+g40f1cda.d20190711)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
Requirement already satisfied: gpiozero in /usr/lib/python3/dist-packages (from photobooth==0.5.dev3+g40f1cda.d20190711) (1.5.1)
Collecting pycups (from photobooth==0.5.dev3+g40f1cda.d20190711)
  Downloading https://files.pythonhosted.org/packages/00/ce/836a0deb8b24bcd5f850f8fb97f99fb4abd7374e078b9e6df5a0838f8eb5/pycups-1.9.74.tar.bz2 (52kB)
    100% |████████████████████████████████| 61kB 985kB/s 
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from photobooth==0.5.dev3+g40f1cda.d20190711) (2.21.0)
Building wheels for collected packages: pycups
  Running setup.py bdist_wheel for pycups ... done
  Stored in directory: /home/pi/.cache/pip/wheels/bb/4a/db/d9ea6edeead55ff1b909f3e7aa4384db28ff6ce3ecef0c94f7
Successfully built pycups
Installing collected packages: gphoto2, pycups, photobooth
  Running setup.py develop for photobooth
Successfully installed gphoto2-2.0.0 photobooth pycups-1.9.74
pi@raspberrypi:~/Desktop/photobooth $ 
```

**Comment by reuterbal** [comment]
I recommend creating a virtual environment (see [this point](https://github.com/reuterbal/photobooth/blob/master/INSTALL.md#initialize-virtualenv) of the installation instructions). That way, you can have multiple versions of the same Python packages on the system.

Good to know that OpenCV is the only package missing on Buster. Maybe we should make that optional as hardly anyone seems to use webcams anyways.

**Comment by poldixd** [comment]
> I recommend creating a virtual environment (see [this point](https://github.com/reuterbal/photobooth/blob/master/INSTALL.md#initialize-virtualenv) of the installation instructions). That way, you can have multiple versions of the same Python packages on the system.

ah, ok, I created the virtual environment at the beginning, but I did not know for what it was.

Thanks for your help and for the photobooth software.
