### ISSUE TITLE
Stuck at installing Photobooth

### ISSUE THREAD

**Issue by HeavyMettAal** [reuterbal/photobooth#160]
Hello,
I need some help installing Photobooth on Raspi 3. I am stuck and do not know what to do. 

Step: "Install photobooth with dependencies"
when I type: "pip install -e ." I get a strange error. 

> (.venv) pi@raspberrypi:~/photobooth $ pip install -e .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Obtaining file:///home/pi/photobooth
Collecting opencv-python (from photobooth==0.5.dev3+g40f1cda)
  ERROR: Could not find a version that satisfies the requirement opencv-python (from photobooth==0.5.dev3+g40f1cda) (from versions: none)
ERROR: No matching distribution found for opencv-python (from photobooth==0.5.dev3+g40f1cda)
(.venv) pi@raspberrypi:~/photobooth $ 

It is probably something super simple, and I am too stupid to find it :-) Please help me. Photobooth looks amazing and I would love to get it running.

Setup: RaspberryPi 3, newest Raspian (Buster with Desktop)

**Comment by reuterbal** [comment]
This is a known issue (see #151) but unfortunately nothing that we can fix. See https://github.com/reuterbal/photobooth/issues/151#issuecomment-510380130 for a temporary solution.
