### ISSUE TITLE
Compact Printing photobooth

### ISSUE THREAD

**Issue by andyboeh** [reuterbal/photobooth#180]
**Describe your photobooth**

I built the box for weddings and parties - the first successful use was at a friend's party. I wanted my box to be very compact and all-in-one, so I came up with a 40cm x 30cm x 30cm wooden case. Everything is included in the box, it's based on a Raspberry Pi and a Selphy printer.

**Hardware:**
 - Raspberry Pi 3B + RTC module
 - 7" Official Raspberry Pi Touchscreen
 - Canon EOS 450D
 - Neewer NW670 TTL Flash + Extension Cord
 - GPIO: No
 - Canon Selphy CP1300

**Software:**
 - Raspbian Buster

**Modifications:**
The Raspberry Pi rootfs was switched to read-only mode and I added an overlayfs for read-write. In order to store pictures, I added a python script that checks for a USB drive on startup and, if found, mounts it. I then modifies the photobooth configuration and starts photobooth. This has the nice side-effect that it also acts as a splash screen. Currently, the script lives in my fork in the supplementals directory: https://github.com/andyboeh/photobooth/blob/usb_device/supplementals/autostart_usb.py
The scripts used to create the read-only root can be found here: https://github.com/andyboeh/root-ro (fork)

**Problems:**
 - For no obvious reason, the power supply of the camera died after two hours of use. Fortunately, it's a 5V 3A USB supply and the 5V 2A supply of a party guest worked just as well.
 - The printer is connected via WiFi and sometimes the printer stopped printing (happened twice). I connected from my cell phone vis SSH and restarted CUPS, then printing resumed. I am going to add a script to automate restarting CUPS if a job stalls.
 - I noticed that the printer compartment gets rather warm. I will add a fan.
 - Very rarely the flash didn't fire. I suppose that the power supply is a bit too weak (5V 4A supply I had lying around) or that it's getting too warm. I'll cover this compartment with the fan as well.

**Planned modifications:**
 - Fan for cooling the printer compartment
 - Externally accessible USB port
 - Externally accessible LAN port
 - Printer/CUPS governor script that restarts either printing or the print server

**Pictures:**
![IMG_20190901_135411](https://user-images.githubusercontent.com/3099753/64927870-a3299b00-d810-11e9-854d-b165ac2fe52a.jpg)
Camera is mounted on the bottom, using a screw on the bottom side, it can be tilted.

![IMG_20190901_140213](https://user-images.githubusercontent.com/3099753/64927871-a3c23180-d810-11e9-8a28-d7b78f6f5bd7.jpg)
Canon Printer

![IMG_20190901_140224](https://user-images.githubusercontent.com/3099753/64927872-a3c23180-d810-11e9-823d-0a8190bb87ee.jpg)
Canon Printer

![IMG_20190901_142041](https://user-images.githubusercontent.com/3099753/64927873-a3c23180-d810-11e9-8ef9-e8439407106b.jpg)
The flash was not modified, but an AA battery adapter was used. The PSU is a cheap 5V/4A supply that I had lying around.

![IMG_20190901_171515](https://user-images.githubusercontent.com/3099753/64927935-8e013c00-d811-11e9-9840-dcc88597f2fb.jpg)
Completed box

![IMG_20190903_132132](https://user-images.githubusercontent.com/3099753/64927875-a3c23180-d810-11e9-822c-dbdfd5894d26.jpg)
Printer at the side of the box

![IMG_20190903_132149](https://user-images.githubusercontent.com/3099753/64927876-a45ac800-d810-11e9-9d64-8486819d8cc2.jpg)
Printer is accessible for replacing cartridges

![IMG_20190903_132156](https://user-images.githubusercontent.com/3099753/64927877-a45ac800-d810-11e9-852f-99b54c2c1cae.jpg)
Printer is accessible for replacing cartridges

**Comment by thyristor59** [comment]
hello, very nice box !!!
 having to manually restart CUPS every time I change ink and / or paper. 
I  would be curious to see the scrips to no longer have to do it manually! would be nice

**Comment by andyboeh** [comment]
@thyristor59 I'll post/link the scripts here as soon as they are ready - might take a few days.

**Comment by andyboeh** [comment]
@thyristor59 I tried to reproduce the CUPS problem at home, but I don't want to waste much photo paper. So far, I wasn't able to get cups in a state where I wouldn't continue on its own. Do you know how to trigger this behavior? Running out of paper is not enough in mine case, it continues fine after paper has been added.

**Comment by oelegeirnaert** [comment]
Hi @andyboeh ,

What's the name of the fabric you used to cover the wooden case?

Kind regards,
Oele Geirnaert

**Comment by andyboeh** [comment]
That's felt used for building speakers - I used some leftovers from the subwoofers I built a while back. I used spray adhesive, but you can buy the felt with adhesive on.

The red door is covered using a self-adhesive foil.

**Comment by andyboeh** [comment]
Closing since it has been added to the Wiki.
