### ISSUE TITLE
hit the BUTTON is not working

### ISSUE THREAD

**Issue by buchey8070** [reuterbal/photobooth#23]
Hi there,

I just found your project and want to use this at a wedding next time. Setup will be a Pi B+, 800x600 touchscreen and a picamera. 
If I start the photobooth, I get to "Hit the button", but unfortunately it doesn't work. There's no output in the log or something.

You got this behavior before?

**Comment by hollesse** [comment]
Check this issue here. https://github.com/reuterbal/photobooth/issues/22

**Comment by reuterbal** [comment]
Hi,
yes, the buttons don't work yet, as mentioned in the issue referenced by @hollesse . I included them in the GUI layout but didn't have time yet to include them properly.
