### ISSUE TITLE
[Install] Hash error during "pip install -e ." step.

### ISSUE THREAD

**Issue by ir0nh3at** [reuterbal/photobooth#36]
**Describe the bug**

When following the installation instructions, all goes well until the "pip install -e ." step.  At that point I receive hash errors that I can't seem to bypass.  I found some suggestions online to try --no-index and --no-cache-dir, neither seems to work.  Output of "pip install -vvv -e ." attached.

Thanks for taking a look.  I'm really trying to get this done this weekend if at all possible.  Thank you!

[pip.txt](https://github.com/reuterbal/photobooth/files/2256171/pip.txt)

**Comment by ir0nh3at** [comment]
So I swapped out the SD card - it was pretty slow, so I thought it might have been damaged.  I started from the beginning and had the same issue again with gphoto2.  I then removed it as you suggested and opencv-python errored out again.

I need opencv as I'll be using a Microsoft webcam.  I guess I'll try it on a laptop and see if I have any better luck than the pi.

**Comment by ir0nh3at** [comment]
I just followed the instructions on a Mint VM and they worked correctly, no errors.  It looks like it's something with the Pi.  Super frustrating...

**Comment by reuterbal** [comment]
If you find out more, please tell us about it. As the installation seems to work for others, I consider this not to be a general problem and will close this.
