### ISSUE TITLE
Can't change the print out to 4 horizontals on a strip

### ISSUE THREAD

**Issue by garybreck** [reuterbal/photobooth#39]
I build a portable Photobooth  for Berning Man 

Everything is mounted in a small pelican case
Raspberry Pie 3 B+ 
Mini thermal printer (USB)
Canon Rebel T2i 
Raspberry 7 inch Touchscreen
External USB battery

Raspbian Stretch
Python version 3.5.1

Problem,
when "number of shots per picture" is set out to 4 by 1 , it prints them across (side by side) to fit on the 58mm with of the paper.
Is there any way to change it, so its 4 horizontal Photos one on top of the other like the old school photo booths?

Thanks for your Help
Gary 

 

![img_0110 2](https://user-images.githubusercontent.com/41706360/44043411-d2e003de-9ef0-11e8-9192-2351bc3db1b1.jpg)
![img_0107](https://user-images.githubusercontent.com/41706360/44043412-d2ec4f7c-9ef0-11e8-827e-e9245b59436a.jpg)
![img_0111](https://user-images.githubusercontent.com/41706360/44043413-d2fc9bb6-9ef0-11e8-9d93-c663de90f38d.jpg)

**Comment by wikijm** [comment]
Hi  @garybreck,

Here is an example of configuration you can use:
![screenshot from 2018-08-13 14-23-36](https://user-images.githubusercontent.com/10724809/44051398-095800bc-9f3a-11e8-8e27-17f481c1752b.png)

And the result:
![photobooth00001v2](https://user-images.githubusercontent.com/10724809/44051433-262abbb2-9f3a-11e8-9615-695dff0296a2.jpg)

Is this fit your needs?

**Comment by garybreck** [comment]
Thanks seemed to do the trick! Along with changing the "size of the assembled picture"  now it works.
Thanks

**Comment by thyristor59** [comment]
I tried to make a change for myself when I start the program, it launches a very small page and bueu completely. until reboot the raspberry 😢

I will restart a new memory cars?

**Comment by wikijm** [comment]
Hi @thyristor59 

Before you consider a complete reinstallation of your Raspberry, you can try to redo the entire Photobooth installation process.

If you wish to keep a copy of your current installation, remember to rename the folder containing it (I imagine `/home/pi/photobooth` in your case).

**Comment by thyristor59** [comment]
![img_20180815_144413_hdr](https://user-images.githubusercontent.com/42303881/44148748-d4b8a0bc-a099-11e8-830d-da4899459a63.jpg)

Why i have %y-%m-%d?? And not /Home/user/pi??

**Comment by wikijm** [comment]
%Y => Year
%M => Month
%D => Day

With %Y-%M-%D value, a folder with the actual date will be created in /home/pi/photobooth/ directory.
You still have the ability to define a personalized directory if you prefer.
