### ISSUE TITLE
Show Preview all the time 

### ISSUE THREAD

**Issue by karatektus** [reuterbal/photobooth#48]
Would be nice, to be able to see the preview all the time and a push on the button only starts the countdown

**Comment by reuterbal** [comment]
It will require some work but it is doable to add a preview functionality to the idle screen - basically, you would have to add the relevant code parts from PreviewState to IdleState in the gui module and the camera module.

However, I would not recommend doing so using a DSLR - the nonstop use of the sensor might heat it up on older models that are not yet optimized to nonstop video applications. It's not guaranteed to be a problem, of course.
In any case, it will probably heat up the sensor and thus increase noise, which is an issue in low-light situations already (at least for me).

Thus, I'm not going to add it - however, feel free to add it yoursel (preferably optionally via a config setting). I'm happy to provide any guidance where needed.

**Comment by thyristor59** [comment]
would it be useful?

https://github.com/aqiank/gphoto2-liveview-example

**Comment by rossturv** [comment]
Would it be possible to use a usb webcam to show the live preview but still use a dslr as the main capture device? This would be a great option for myself as I am trying to set this up using a canon 350D which does not have the live-view option.
Great project by the way!

**Comment by wikijm** [comment]
Hi @rossturv,

I faced to the same problem before working with a 650D model.

How about using a mirror?
Not necessarily the cheapest solution, but certainly the easiest to implement 😜

**Comment by thyristor59** [comment]
that does not prevent us from not knowing if we are in the frame of the camera

**Comment by reuterbal** [comment]
Hi,

regarding your comments, I'll answer them one by one:

@rossturv asked:

> Would it be possible to use a usb webcam to show the live preview but still use a dslr as the main capture device? 

From a technical point of view this is possible, however it requires quite some programming work.
Moreover, it would be cumbersome to align the angle of view of both cameras when setting up the photobooth.Thus I do not consider that a good option.

@thyristor59 wrote about the use of a mirror:
> that does not prevent us from not knowing if we are in the frame of the camera

The same problem applies to a webcam (see above). The preview during countdown is specifically for that sake: knowing that you are in the frame of the camera and positioning yourself. If you find that time too short, simply increase the countdown length.

@thyristor59 wrote:
> would it be useful? https://github.com/aqiank/gphoto2-liveview-example

Liveview is already implemented during countdown.

**Comment by reuterbal** [comment]
I'm labelling this as "help wanted" and closing the issue as I'm not able to add this feature in the near future. Feel free to implement it and open a pull request!
