### ISSUE TITLE
Webcam do not work / OpenCV issue?

### ISSUE THREAD

**Issue by qwertyFrank** [reuterbal/photobooth#78]
Hi all,
I’m using Raspbian Desktop and rpi 3B+.
I would like to use a webcam instead a picam. I plugged in a webcam (apeman 4K) via USB to rpi and selected OpenCV by using configuration screen in Photobooth. But it doesn’t work. Even Photobooth did not start and “hang” in start mode. Do I have to install OpenCV (ver 3 or 4?) in addition?
Thanks for any hint.
Best regards,
Frank

**Comment by wikijm** [comment]
Hi @qwertyFrank 

In order to help you as much as possible, can you provide what is required when creating an issue ticket?

Sincerely,
WikiJM

**Comment by reuterbal** [comment]
Are you sure that your installation went through without errors? There is no package `opencv-python` installed, which is required to use a webcam.
Try `pip install opencv-python` to add the failing dependency.

**Comment by reuterbal** [comment]
Did that help?

**Comment by qwertyFrank** [comment]
Hi,
I'm using RPI camera now. Did not follow up Web cam anymore, therefore did not try your proposal.
Thanks

**Comment by reuterbal** [comment]
Ok, closing this.

**Comment by Wikinaut** [comment]
@qwertyFrank see https://github.com/reuterbal/photobooth/issues/68
