### ISSUE TITLE
Canon Selphy CP800 suddenly not printing anymore

### ISSUE THREAD

**Issue by jul1792** [reuterbal/photobooth#79]
Hi everybody,

I already used the photobooth a couple of times and already posted a success story, which you can find [here](https://github.com/reuterbal/photobooth/issues/73). Everything worked great!

But last week I went to a New Years Eve party and brought my photobooth with me. I plugged it in and took a test shot. Everything worked great, the photo was printed automatically. Then the photobooth stood there, turned on and ready. But after two hours, when we wanted to start taking some snapshots, it stopped working: It took photos perfectly, but it did not print anymore (I set the settings to not ask if I wanted them to print, but just to print every photo automatically). And this is the status right now. Photos are taken, but my Canon Selphy CP800 just doesn't react anymore. The photos are even saved.

When I type in `lpstat -p -d` it says: "No paper tray loaded, aborting!"

I also tried to delete the printer in cups, but then I have to authenticate but my username "pi" and the default password do not work. Also I tried to print a test photo, but that didn't work either. In Cups the status is the same as `lpstat -p -d`: "No paper tray loaded, aborting!"

I then unplugged the printer, inserted a SD card and printed a photo. This did work great! So the printer should not be the problem.

What can I do to solve the problem? Has anyone any suggestions?

Thanks a lot in advance!

My setup:

- Raspberry Pi 3
- Raspberry Camera Module v2.1
- Canon Selphy CP800

![foto 05 01 19 10 56 20](https://user-images.githubusercontent.com/25178619/50723712-86fe2780-10e1-11e9-8c4f-2eb27ef4d577.jpg)
![foto 05 01 19 10 56 36](https://user-images.githubusercontent.com/25178619/50723713-86fe2780-10e1-11e9-94d4-1cc43001b8b5.jpg)
![foto 05 01 19 11 10 36](https://user-images.githubusercontent.com/25178619/50723714-86fe2780-10e1-11e9-8297-6b84ed8261f4.jpg)

**Comment by reuterbal** [comment]
To modify the printer settings in CUPS, you have to add the user `pi` to the group `lpadmin`, as explained in the [installation instructions](https://github.com/reuterbal/photobooth/blob/master/INSTALL.md#add-user-pi-to-group-lpadmin)

I'd try removing and re-adding the printer.

**Comment by reuterbal** [comment]
Any progress?

**Comment by jul1792** [comment]
Sorry, I didn't answer for so long.
I tried to add the user `pi` to the group `lpadmin` as described in the installation instructions. But in CUPS I could not delete the printer with user `pi`. I even changed the default password of `pi` with the command `sudo passwd`. But still no luck.

I will have some spare time on the weekend and do a backup of the current System. Then I will begin from the start and will install everything from scratch again. I hope this does the trick. I will let you know.

If you have any other solutions in the meantime, I will be happy to try them out :)

Thanks a lot!

**Comment by reuterbal** [comment]
With `sudo passwd` you have changed the password of the root user. Simply run `passwd` to change the password of the user `pi`.

**Comment by reuterbal** [comment]
What does `getent group lpadmin` say?

**Comment by jul1792** [comment]
`getent group lpadmin` Says `lpadmin:x:114:pi`

With command `passwd` I have to enter the current password and I just can‘t remember it. 

Is there a way to remove CUPS and install it again?

I also tried to install everything from scratch but that failed in another part. I opened an issue with this here: 
https://github.com/reuterbal/photobooth/issues/100

**Comment by reuterbal** [comment]
To reset the password of the `pi` user, run `sudo passwd pi` and enter the root password (i.e., the one that you specified by running `sudo passwd` earlier). If you don't remember that either, re-install everything and read up a little bit about Linux in general.

To reinstall CUPS, run the following:
1. Remove everything including configuration
`sudo apt purge cups`
(Pay attention to the list of packages that is removed. If something is not working later on, you might have to add some of the automatically removed packages by hand later on).
2. Install CUPS
`sudo apt install cups`
3. Install gutenprint or whatever else you need.
