### ISSUE TITLE
Success story: Photobooth 1.0

### ISSUE THREAD

**Issue by reuterbal** [reuterbal/photobooth#85]
**Describe your photobooth**
This photobooth was the reason for the rewrite of the initial software version. The original motivation was a friend's wedding but it has been used before that and afterwards at a couple of events

**Hardware (please complete the following information):**
 - Raspberry Pi 3B
 - Canon EOS 500D with Canon EF 28mm f2.8 lens
 - GPIO: Trigger-button, Trigger-LED, Exit-LED (inside the housing), color LED-strip
 - Canon Selphy CP1300 (connected via USB)
 
 **Additional equipment**
  - Cheap studio lamp from Amazon
  - External USB battery
  - External power supply for camera
  - 1024x600px touch screen from Pollin
  - Emergency-switch with lamp from eBay (230V lamp replaced by 12V LED)
  - LED strip for lighting during idle, red blinking during countdown, and white light (as "flash")

**Software (please complete the following information):**
 - Latest Raspbian
 - 3.5.x

**Modifications:**
 - This is the original setup from the repository. Modifications not included in the repository are only custom backgrounds for the assembled pictures.

**Problems:**
 - Printer hangs (presumably only when there is a longer print queue). It just stays displaying "busy". Most of the times it helps to unplug the power supply of the printer and to turn it back on. It then continues to print missing photos. Sometimes, jobs in the queue are put on hold and must be re-enabled in CUPS. No idea how to fix this, as CUPS has the jobs...
- I experienced once or twice out-of-memory issues or a random hang of the photobooth without anything in the logs. Keep an eye out ;-)

**Pictures:**
Some pictures from the setup of an event at the weekend. This is usually what it looks like:
- Photobooth + Studio lamp
- Some background
- Printer and masks on a nearby table
- Photo-album and some handicraft work equipment to glue photos in and create a guest-book on-site.
![img_20190112_182331](https://user-images.githubusercontent.com/6384870/51106379-e3e99400-17eb-11e9-90d1-52422d0acb09.jpg)
![img_20190112_182321](https://user-images.githubusercontent.com/6384870/51106380-e3e99400-17eb-11e9-97fc-620e52367937.jpg)
![img_20190112_182309](https://user-images.githubusercontent.com/6384870/51106381-e3e99400-17eb-11e9-9f71-3ad203144c4a.jpg)
Some older photos from the interior and tests in my living room:
![img_20180823_211044](https://user-images.githubusercontent.com/6384870/51106777-0e881c80-17ed-11e9-8ad2-083dc27febf0.jpg)
![img_20180823_211012](https://user-images.githubusercontent.com/6384870/51106779-0f20b300-17ed-11e9-987b-de11d3ce1f4b.jpg)
![img_20180823_210945](https://user-images.githubusercontent.com/6384870/51106780-0f20b300-17ed-11e9-9840-ba5199cfb976.jpg)

**Comment by qwertyFrank** [comment]
Looks very good. Can you share the schematics, componentes used to drive color LED-strip? Which LED-strip did you use?
Thanks in advance.

**Comment by botyas** [comment]
I have the assembly that appears on this plane  `photobooth/supplementals/wiring/wiring_bb.png`
       with the circuits that I retrubal indicated to me [in this answer](https://github.com/reuterbal/photobooth/issues/65#issuecomment-435306123)  and it works correctly.

**Comment by reuterbal** [comment]
The wiring schematics linked to by @botyas are mine, the LED strip is included there as red/green/blue LEDs. Some info about the LED strip is included in #26

**Comment by thyristor59** [comment]
great, great job !!
how did you get the liveview shown on the screen?
would you have the reference of the amazon lamp?
thank you in advance !

**Comment by reuterbal** [comment]
Live view is an intrinsic component of the software package? How do you not get it?

The lamp could be this one: https://www.amazon.de/dp/B01EFDROV0/

**Comment by reuterbal** [comment]
Closing this as the story is in the wiki.
