### ISSUE TITLE
Question: Can I center the text?

### ISSUE THREAD

**Issue by raeMaem** [reuterbal/photobooth#88]
Hello and thanks for this awesome, well made, really complete project.

Instead of the text saying "Press the button" with the arrow, I've deleted the arrow files and replaced the text by "Press the screen" because I want to use a touchscreen instead. Until here I was fine, but can you tell me how I can center the text please? The text is still here as if the arrows were on the right and it's not centered.

Once again thanks for this awesome project

**Comment by MarioJanssen27** [comment]
Hello raeMaem, 

I think your problem is already being discussed and explained here. Link: [https://github.com/reuterbal/photobooth/issues/82#issuecomment-454300816]

**Comment by raeMaem** [comment]
Hello MarioJanssen27,

You're totally right. I had started to read that discussion but didn't follow through the end, sorry.

Thank you for your help.

**Comment by reuterbal** [comment]
Thanks for the link, closing this as a duplicate.
