### ISSUE TITLE
[rpi camera] camera not detected.

### ISSUE THREAD

**Issue by jsitges** [reuterbal/photobooth#9]
Does this project is able to work with rpi camera v2?
I tried with both gphoto and cv camera modules, also deactivated the preview.
i get this error in photobooth.err
```
Traceback (most recent call last):
  File "photobooth.py", line 6, in <module>
    from glob import glob
  File "/usr/lib/python2.7/glob.py", line 1, in <module>
    """Filename globbing utility."""
KeyboardInterrupt

```
and this in the log:
```
OpenCV available
Info: Number of last existing file: 0
Info: Saving assembled pictures as: 2018-05-12/picXXXXX.jpgOpenCV available
Info: Number of last existing file: 0
Info: Saving assembled pictures as: 2018-05-12/picXXXXX.jpg
Your Raspberry Pi is board revision 3
RPi.GPIO version is 0.6.3
SERIOUS ERROR: GuiException("ERROR: Can't open image '/tmp/photobooth_preview.jpg': Unsupported image format",)
Error: SERIOUS ERROR!
```
i instaled the python bindings for gphoto, and the files supposed to be deleted were not there to be deleted.
thank you for a wonderful project.

**Comment by reuterbal** [comment]
Dear jsitges,
currently there is no support for the RPi camera modules - however, it is on my agenda to add this eventually to the new version that I'm currently developing in the branch 'development'.

**Comment by reuterbal** [comment]
RPi camera module is suppported as of now.
