### ISSUE TITLE
by autostart not any more write access permissions for writing picture on USB

### ISSUE THREAD

**Issue by qwertyFrank** [reuterbal/photobooth#93]
**Describe the bug**
Hi,
until now I started photobooth manually by start of RPI with user pi, going to directory phootobooth and using autostart.sh.
I configured the system in such way that all picutures are stored on a USB sitck using pi/media directory.

Now I enabled autostart option as shown in the Wiki https://github.com/reuterbal/photobooth/wiki/Tips-and-tricks

Photobooth starts fine, but I got error message, after taking picture and try to store such picture on the USB stick. No access permisssion.

How to solve?

Thanks

**Comment by reuterbal** [comment]
This has probably something to do with the drive not being mounted automatically after reboot. Try mounting the USB drive explicitly, e.g., by following the instructions [linked here under 3.](https://github.com/reuterbal/photobooth/issues/89#issuecomment-454752896)

**Comment by qwertyFrank** [comment]
Works perfect. Thanks.

**Comment by reuterbal** [comment]
Glad to hear. Closing this.
