### ISSUE TITLE
Increase photo resolution / RPI camera

### ISSUE THREAD

**Issue by qwertyFrank** [reuterbal/photobooth#95]
Hi,
How can I increase the photo resulation using RPI camera? Where to modify? 
Thanks

**Comment by reuterbal** [comment]
You're in the right place and the last line looks correct.
See the documentation: https://picamera.readthedocs.io/en/release-1.13/api_camera.html#picamera.PiCamera.capture
Without a log or an error message I'm unable to help.

**Comment by qwertyFrank** [comment]
I got the failure. Put "tabs" instead of "blanks" in the py-file. Using "blanks" only => it works perfect,
Sorry for confusion.

**Comment by reuterbal** [comment]
Great. Closing this.
